### ISSUE TITLE
Preserving special characters

### ISSUE THREAD

**Issue by lessless** [flavorjones/loofah#106]
Hello,

This is a very old and well-known  Nokogiri issue of preserving special characters like `&nbsp;`. 
The basic recipe to encode parsed string in ASCII-8BIT-  https://groups.google.com/forum/#!topic/nokogiri-talk/Q2Nh1cLeQzk, then it will not substitute those special characters. 
But, unfortunately this is not working with Loofah:

```
text = "</div><ul><li>Simple example&nbsp;</li></ul><div>"
doc = Loofah.fragment(text.encode('ASCII-8BIT'))
doc.inner_html
output error : unknown encoding ASCII-8BIT
output error : unknown encoding ASCII-8BIT
=> ""
```

**Comment by flavorjones** [comment]
Sorry, you haven't mentioned what version of Ruby, Nokogiri, or Loofah you're using, but I do see this behavior with ruby 2.4.0 / nokogiri 1.7.0.1 / loofah 2.0.3.

Though, I'm not sure what you're trying to do, as with those versions things work just fine without trying to force encoding:

```
#!/usr/bin/env ruby

require 'loofah'

text = "</div><ul><li>Simple example&nbsp;</li></ul><div>"
puts text.encoding
# => UTF-8
doc = Loofah.fragment(text)
puts doc.inner_html
# => <ul><li>Simple example </li></ul><div></div>
```

Can you help me understand what you're trying to do?

**Comment by flavorjones** [comment]
I can't reproduce this using Ruby 2.5 and Loofah 2.1.1.

**Comment by mikesnare** [comment]
I think the point is to preserve the `&nbsp;` that was originally in the HTML.  I'm running into this same problem.  The client is providing `&nbsp;` entities and when I use Loofah to scrub the input the `&nbsp;` entities are removed.  Anywhere an `&nbsp;` is encountered in the text it is replaced with a simple space.  Not sure how I can address it, since the linked google forum post's suggestion of using ASCII-8BIT encoding just causes errors.

**Comment by LachlanCourtSPP** [comment]
I also have the same problem as @mikesnare did this ever get addressed?

**Comment by flavorjones** [comment]
@LachlanCourtSPP Please open a new issue and help me to reproduce what you're seeing with working code. Thanks.

**Comment by wizardofosmium** [comment]
Has a new issue (and fix?) been created?  Googling "loofah removes &nbsp;" comes here.
```ruby
Loofah.fragment("&amp;nbsp; != &nbsp;").scrub!(:prune).to_s
=> "&amp;nbsp; !=  "
```
should be `"&amp;nbsp; != &nbsp;"`

Ruby: 2.7.4p191
Loofah: 2.18.0
Nokogiri: 1.13.7
