### ISSUE TITLE
Sanitize doesn't work with -webkit in style

### ISSUE THREAD

**Issue by iggant** [flavorjones/loofah#109]
Rails is using loofah for sanitaze strings, but I don't know with methods, can I provide rails example, but if you'd need for specific example, I'll dig into that methods

it doesn't process tags style correctlly if it contain custom styles (for instance: all -webkit- prefix)

```
body = "<a href=\"https://someurl_doesnt_matter/el\" style=\"display: inline-block;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;background-color: #3AAEE0;color: #ffffff\" target=\"_blank\">"

ActionController::Base.helpers.sanitize(body, :tags => ["a"], :attributes => %w(href style target) ) 
```

return

> `<a href=\"https://someurl_doesnt_matter/el\" style target=\"_blank\"></a>`

while

```
body = "<a href=\"https://someurl_doesnt_matter/el\" style=\"display: inline-block;text-decoration: none;text-align: center;background-color: #3AAEE0;color: #ffffff\" target=\"_blank\">"

ActionController::Base.helpers.sanitize(body, :tags => ["a"], :attributes => %w(href style target) )
```

works fine

> `<a href=\"https://someurl_doesnt_matter/el\" style=\"display: inline-block; text-decoration: none; text-align: center; background-color: #3AAEE0; color: #ffffff;\" target=\"_blank\"></a>`

**Comment by flavorjones** [comment]
This appears to have been fixed in v2.1.0 with the introduction of the Crass gem to do CSS style parsing.
