### ISSUE TITLE
sanitize removes everything after chevron

### ISSUE THREAD

**Issue by jvenezia** [flavorjones/loofah#111]
I have a weird behaviour in production with the `sanitize` method.

In my local machine, it works as I expected: 
```
$ Loofah::Helpers.sanitize 'some < text'
=> "some &lt; text"
```

In production (heroku): 
```
$ Loofah::Helpers.sanitize 'some < text'
=> "some "
```

Do you have any idea ?
What is the expected behaviour and how could it be different in my machine and heroku's.

I'm using `loofah 2.0.3`

**Comment by jvenezia** [comment]
I just realized that the problem is from Nokogiri. Same behaviour with `Nokogiri::HTML.fragment('some < text').to_s`.

**Comment by flavorjones** [comment]
Likely this is due to varying versions of libxml2 in your dev environment and your production environment.

**Comment by jvenezia** [comment]
Thanks @flavorjones , related to https://github.com/sparklemotion/nokogiri/issues/1527
