### ISSUE TITLE
Sanitize remove all text in the style

### ISSUE THREAD

**Issue by iggant** [flavorjones/loofah#115]
`<p style="margin:0px 0px 4px;font-size:14px;font-family:courier,helvetica,sans-serif;color:rgb(0,0,0);text-decoration:none"><strong>Some text</strong></p> =>  <p style=""><strong>Some text</strong></p>`

but after I delete letter-spacing:-0.5px;word-spacing:1px;

every thing works fine:

`<p style="margin:0px 0px 4px;font-size:14px;font-family:courier,helvetica,sans-serif;color:rgb(0,0,0);text-decoration:none"><strong>Some text</strong></p> => <p style="margin:0px 0px 4px;font-size:14px;font-family:courier,helvetica,sans-serif;color:rgb(0,0,0);text-decoration:none"><strong>Some text</strong></p>`

**Comment by flavorjones** [comment]
Hi,

Please provide a full example of the code you're running, along with Ruby, Nokogiri, and Loofah versions.

**Comment by flavorjones** [comment]
Closing, pending more information from the OP
