### ISSUE TITLE
Problem with scrub_css when value is rgb

### ISSUE THREAD

**Issue by SavenkoSy** [flavorjones/loofah#129]
After updated from `2.0.3` -> '2.1.1'

When the version is `2.0.3`:
`Loofah::HTML5::Scrub.scrub_css "color: rgb(255, 0, 0)"`
`=> "color: rgb(255, 0, 0);"`

When the version is `2.1.1`:
`Loofah::HTML5::Scrub.scrub_css "color: rgb(255, 0, 0)"`
`=> ""`

**Comment by tschoppi** [comment]
Might be solved with manual intervention after #123 has been merged.

**Comment by flavorjones** [comment]
Will be fixed in the next release, likely named v2.2.0.
