### ISSUE TITLE
Whitelist the HTML5 <main> element

### ISSUE THREAD

**Issue by MothOnMars** [flavorjones/loofah#133]
I'd like content within the `main` element to be preserved. Currently, it's removed when scrubbing:

```ruby
html = "<body>body<main>main</main></body>"
Loofah.fragment(html).scrub!(:whitewash)
# =>  <body>body</body>
```

Reference: https://www.w3schools.com/tags/tag_main.asp

**Comment by flavorjones** [comment]
Hi Martha,

Thanks for bringing this up! I can't think of any reason not to consider this. Let's continue the conversation in the PR.
