### ISSUE TITLE
add html5 block elements to STRICT_BLOCK_LEVEL set

### ISSUE THREAD

**Issue by MothOnMars** [flavorjones/loofah#135]
Loofah's `to_text` method is not properly adding line breaks between HTML5 block-level elements, i.e.:
```ruby
> Loofah.fragment("<body>Body<main>Main</main></body>").to_text
"BodyMain"
```

This appears to be happening because the STRICT_BLOCK_LEVEL set is missing HTML5 block-level elements, including `<main>`. The HTML5 block-level elements that should be added are:
article
aside
canvas
details
figcaption
figure
footer
header
main
nav
section
summary

Related to https://github.com/flavorjones/loofah/issues/12.

References:
https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements
https://www.w3schools.com/tags/tag_summary.asp
https://www.w3schools.com/tags/tag_details.asp

**Comment by flavorjones** [comment]
This looks good to me! Going to add one commit afterwards to clean it up a bit and add a test.

Thank you for this contribution!

**Comment by MothOnMars** [comment]
Thanks!
