### ISSUE TITLE
Add to README: Does not have the Nokogiri XXE DTDLOAD/NONET vulnerability

### ISSUE THREAD

**Issue by david-a-wheeler** [flavorjones/loofah#140]
As you know, Nokogiri gem can analyze HTML and XML.  Nokogiri can be used in a dangerous way if DTDLOAD is enabled and NONET is disabled (this enables XXE attacks), and some tools are thus reporting Loofah as a potential security vulnerability because it uses Nokogiri.

As far as I can tell, loofah never enables DTDLOAD, and it never disables NONET, so loofah doesn't use Nokogiri in an insecure way.

If that's true, please add something about that in the loofah README, e.g.:

> Some tools may incorrectly report loofah is a potential security vulnerability.  Loofah depends on Nokogiri, and it's possible to use Nokogiri in a dangerous way (by enabling its DTDLOAD option and disabling its NONET option).  This dangerous Nokogiri configuration, which is sometimes used by other components, can create an XML External Entity (XXE) vulnerability if the XML data is not trusted. However, loofah never creates this dangerous configuration; loofah never enables DTDLOAD, and it never disables NONET.

**Comment by flavorjones** [comment]
Hi there! Thanks for bringing this up.

Can you help me understand more deeply the problem that you're trying to solve? Who is this documentation intended to communicate with?

Nokogiri itself has documented that, by default, it treats all documents as untrusted, and so DTDLOAD and NONET are set to secure values of `false` and `true` respectively. This was addressed in https://github.com/sparklemotion/nokogiri/issues/1583 by commit https://github.com/sparklemotion/nokogiri/commit/3b9d2ff29295a474d47603350b34a92ac6140925

**Comment by david-a-wheeler** [comment]
Sure!

There are a variety of tools that analyze software to help identify vulnerabilities.  I lead the [CII Best Practices Badge project](https://github.com/coreinfrastructure/best-practices-badge/), and since we don't want vulnerabilities, we use multiple tools to help us find potential problems.

An [analysis by Snyk.io](https://snyk.io/test/github/coreinfrastructure/best-practices-badge?severity=high&severity=medium&severity=low) reported that we were vulnerable because we use loofah, which in turn uses Nokogiri.  I don't think it's actually a vulnerability, for the reason stated above.  However, I think more and more tools that do deeper analysis will have similar reports.  You could argue that it's a failing of the tool... but without clear documentation by loofah, I understand why the tools report what they do.

It's true that Nokogiri by *default* treats documents as untrusted, but tools can't always figure out if other components that *use* Nokogiri are passing dangerous options or not.

It'd be much better if loofah made it clear that it didn't use those dangerous options in Nokogiri.

Thanks.

**Comment by david-a-wheeler** [comment]
As far as users go, it'd be (1) people who analyze programs looking for security flaws, and (2) people who create tools to *help* find security flaws.

**Comment by david-a-wheeler** [comment]
I created PR #141 to address this.

**Comment by flavorjones** [comment]
I'd like to better understand your explanation above. I'm familiar with snyk, but I'm not sure what the relationship is between documentation and the tool's output. Can you help me understand how updating these documents will change snyk's report?

**Comment by david-a-wheeler** [comment]
Updating these documents is useful, whether or not the report of Snyk (and similar tools) changes:
* The Snyk developers are much more likely to remove the report about loofah as a false positive, because they can point to an analysis that explains why there's no problem.  My hope is that this is what happens eventually.
* If the Snyk developers don't remove the report on loofah, then many users of loofah (like me) will have to investigate loofah to determine if loofah uses nokogiri in a dangerous way.  Many developers proactively use *many* tools to look for potential problems. It'd be *way* easier to have that analysis done once, and then other users can quickly determine that there's no problem.

**Comment by flavorjones** [comment]
Fair enough. I'll merge #141, and thank you so much for talking this through. And thank you for contributing a PR!

**Comment by brandondrew** [comment]
> There are a variety of tools that analyze software to help identify vulnerabilities. I lead the [CII Best Practices Badge project](https://github.com/coreinfrastructure/best-practices-badge/), and since we don't want vulnerabilities, we use multiple tools to help us find potential problems.
> 
> An [analysis by Snyk.io](https://snyk.io/test/github/coreinfrastructure/best-practices-badge?severity=high&severity=medium&severity=low) reported that we were vulnerable because we use loofah, which in turn uses Nokogiri. I don't think it's actually a vulnerability, for the reason stated above. 

David, would you be willing to list the tools you used to determine that Snyk's report of a loofah vulnerability was a false positive?  (I have 163 gems using Nokogiri, and am not keen to go through the code of all of them to inspect whether they have real vulnerabilities or not.)

Thanks!!!

**Comment by brandondrew** [comment]
@david-a-wheeler  ^

**Comment by david-a-wheeler** [comment]
@brandondrew - my tools were eyeballs, cerebrum, and grep :-).

I realize that you want me to point to a fancy tool, but I didn't use one in this case.  As noted above, I looked at the Nokogiri documentation which clearly indicates that its defaults avoid the problem... so you just need to ensure that you don't set DTDLOAD to true and NONET to false.  Loofah doesn't set those anywhere (as reported by grep), so unless it does some crazy hackish thing to use parameters without directly using parameter names, all should be okay in this case.  All I needed to do was to confirm that the dangerous parameter settings were not used in this case, and that seemed to do it.

Of course, my analysis could be mistaken, so I posted it so that that the person running the project could confirm or deny the analysis.  Since this change was accepted, I interpret that as confirmation of a correct analysis.

**Comment by brandondrew** [comment]
ahhh, okay, those were the tools I was going to fall back on 🤣 

my other alternative was to monkey-patch Nokogiri to prevent any of the gems from setting DTDLOAD to true or NONET to false... that seems like it may be a paranoia-level precaution, but it may be the only way I can tell my client with extreme confidence that there is no risk 🤔

**Comment by flavorjones** [comment]
@brandondrew Let me know if you want to talk about submitting a PR for something that meets your needs? I'm sensitive to Enterprise Security™ needs and so I'm certain if you have this challenge, so do others. I'd consider merging something that supported a global switch and/or environment variable setting to prevent these settings from being used in combination.

**Comment by david-a-wheeler** [comment]
Much depends on your level of paranoia :-). Using an environment variable to disable dangerous functionality seems helpful. You could set and unset environment variables, so it is no guarantee, but that is lower risk.

Would it be reasomable to move the dangerous functionality into a separately installed plug-in? Then if you don't install the plug-in there is no problem. I suspect most people don't need the functionality anyway, and it'd be more modular.

**Comment by flavorjones** [comment]
I'm actually imagining something like `NOKOGIRI_SAFE_MODE` that disallows any setting that isn't appropriate for an untrusted document. I honestly think it will be a real pain to implement correctly without some heavy-duty refactoring (because there are so many parsing entry points today), but it's technically possible.

But again, I'd ask that you *start* with asserting on your codebase that these options aren't being toggled, because by default Nokogiri adopts a paranoid stance and assumes documents are untrusted, thereby avoiding the class of XXE that this issue was originally opened to better-document.

**Comment by flavorjones** [comment]
Maybe more to the point, though -- the CVE is for libxml 2.9.7 and earlier, it's [resolved in 2.9.8](https://bugzilla.gnome.org/show_bug.cgi?id=772726#c42) which is included in Nokogiri v1.8.3 and later.

Please reconsider whether this is actually an issue with your security folks if you're using v1.8.3 or a later version of Nokogiri.

**Comment by flavorjones** [comment]
PSA: I've also just emailed the Snyk team asking them to update the issue referenced by @david-a-wheeler in https://github.com/flavorjones/loofah/issues/140#issuecomment-360859858
