### ISSUE TITLE
placeholder issue

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/loofah#144]

**Comment by flavorjones** [comment]
This CVE was addressed in Loofah 2.2.1 as noted above.

**Comment by DNNX** [comment]
@flavorjones could you please create and push v2.2.1 tag, and maybe create a new release here on Github?

**Comment by flavorjones** [comment]
@DNNX Apologies, I sometimes forget to push the tag. Done, and I'll document a release.

**Comment by flavorjones** [comment]
Here's a pointer to the upstream libxml2 bug report, for anyone who wants to follow along:

https://bugzilla.gnome.org/show_bug.cgi?id=769760

**Comment by flavorjones** [comment]
Added "References" section linking to related CVEs and upstream bug report and commit.

**Comment by justinhoward** [comment]
MRI hasn't been in use since ruby 1.8.7. It was replaced by YARV. Does that mean that ruby versions greater than that are not vulnerable? Or is YARV also vulnerable?

**Comment by flavorjones** [comment]
@justinhoward I of course mean CRuby, which some still colloquially call "MRI". I'll change the reference, even though I suspect you fully understood what was meant.

**Comment by justinhoward** [comment]
@flavorjones. Thanks! Sorry if I sounded pedantic. I suspected that was the case, but I wasn't aware of the colloquium.

**Comment by iridakos** [comment]
Thanks for your work on this @flavorjones :+1:
