### ISSUE TITLE
Vulnerability issue with nokogiri

### ISSUE THREAD

**Issue by Rushyanth** [flavorjones/loofah#148]
Depends on nokogiri with version => 1.5.9 ie from 1.5.9 to 1.6.0 . There is a vulnerability issue with nokogiri in this version and is fixed in 1.8.2 . But loofah is dependant on lower versions of nokogiri.

**Comment by flavorjones** [comment]
Thanks for pointing this out.

loofah depends on nokogiri `>= 1.5.9`, so there is nothing preventing you from updating your application to use the latest version of nokogiri.

It is not loofah's responsibility to enforce nokogiri security policy, as it's possible (and even preferred in some instances) to configure older versions of nokogiri to use up-to-date system libraries and not the vendored versions of libxml2/libxslt.

I hope this makes sense. You can view a previous conversation about this topic [here](https://github.com/flavorjones/loofah/issues/139#issuecomment-364790429).
