### ISSUE TITLE
Scrub tasks don't clean html tags

### ISSUE THREAD

**Issue by kirylpl** [flavorjones/loofah#151]
Hello everybody,
There is some simple cases below with all HTML sanitizing tasks I found in docs.
Please make me clear about why I can't getting rid of html tags.
Env: Ruby 2.5.1, Loofah 2.0.3, Rails 5.2

```
irb(main):032:0> Loofah.fragment('<p>Test</p><p>Te3st &#13;</p>').scrub!(:strip).to_s
=> "<p>Test</p><p>Te3st \r</p>"
irb(main):033:0> Loofah.fragment('<p>Test</p><p>Te3st &#13;</p>').scrub!(:prune).to_s
=> "<p>Test</p><p>Te3st \r</p>"
irb(main):034:0> Loofah.fragment('<p>Test</p><p>Te3st &#13;</p>').scrub!(:escape).to_s
=> "<p>Test</p><p>Te3st \r</p>"
irb(main):035:0> Loofah.fragment('<p>Test</p><p>Te3st &#13;</p>').scrub!(:whitewash).to_s
=> "<p>Test</p><p>Te3st \r</p>"
```

**Comment by flavorjones** [comment]
@kirylpl I believe you want to use `to_text` and not `to_s`. Please let me know if there's something we can do to clarify this behavior in the README or other documentation?

**Comment by kirylpl** [comment]
@flavorjones I tried with `to_text `method but still have no expected result, unfortunately.
Could you show how to strip example like this? It might be be perfect addition to readme.
```
irb(main):009:0> Loofah.fragment('<p>Test</p><p>Te3st &#13;</p>').scrub!(:strip).to_text
=> "\nTest\n\nTe3st &#13;\n"
irb(main):010:0> Loofah.fragment('<p>Test</p><p>Te3st &#13;</p>').scrub!(:prune).to_text
=> "\nTest\n\nTe3st &#13;\n"
irb(main):011:0> Loofah.fragment('<p>Test</p><p>Te3st &#13;</p>').scrub!(:escape).to_text
=> "\nTest\n\nTe3st &#13;\n"
irb(main):012:0> Loofah.fragment('<p>Test</p><p>Te3st &#13;</p>').scrub!(:whitewash).to_text
=> "\nTest\n\nTe3st &#13;\n"
```

**Comment by kirylpl** [comment]
@flavorjones Yes, I want to get rid of this `&#13;` tag as well as from html tags, kinda combination of `to_text `and not `to_s ` results expected:
`=> "\nTest\n\nTe3st \r\n"`
OR even better if I will have new line only for closing tags  like </p> which situated near openin tags like <p> .
`=> "Test\nTe3st \r"`

**Comment by flavorjones** [comment]
Sounds like you might want to try writing your own scrubber for this behavior! The README has some examples on how you might approach this task.

**Comment by kirylpl** [comment]
@flavorjones  Adding `.gsub(/(&#13;|\s)+/, "\n"),` dealt it for me.
