### ISSUE TITLE
Whitelist certain URLs for scrub!(:nofollow)

### ISSUE THREAD

**Issue by abrambailey** [flavorjones/loofah#157]
I would like to nofollow all links, with the exception of internal links. Is there a way for me to whitelist my own domain?

**Comment by flavorjones** [comment]
Hi @abrambailey! Thanks for asking this question.

The `nofollow` scrubber built into Loofah looks like this:

```
    class NoFollow < Scrubber
      def initialize
        @direction = :top_down
      end

      def scrub(node)
        return CONTINUE unless (node.type == Nokogiri::XML::Node::ELEMENT_NODE) && (node.name == 'a')
        append_attribute(node, 'rel', 'nofollow')
        return STOP
      end
    end
```

The quickest thing for you to do might be to subclass this scrubber, and add your own logic. I can imagine something like (and you should test this to make sure my brain compiled it correctly!):

```
class NofollowExceptMyDomain < Loofah::Scrubbers::NoFollow
  def scrub(node)
    if (node.type == Nokogiri::XML::Node::ELEMENT_NODE) && (node.name == 'a') &&
       is_my_domain(node.attr("href"))
      return CONTINUE
    end
    super
  end
end
```

where the method `is_my_domain` is how you determine whether to allow the tag to go unmodified.

You can then use this scrubber like this:

```
doc.scrub!(NofollowExceptMyDomain.new)
```

I'm also open to a pull request to add this functionality; if you decide you'd like to try that, let's discuss how we might approach it!

**Comment by flavorjones** [comment]
Closing, seems like this is stale, though I hope my response was helpful.
