### ISSUE TITLE
How can I allow liquid tags inside img src attribute without encoding them?

### ISSUE THREAD

**Issue by ndbroadbent** [flavorjones/loofah#160]
I am using Liquid templates, and I am showing a preview to the user in their browser. But I wanted to scrub the HTML first to avoid XSS. Loofah works really well, but there's just one issue in my img src attributes:

```ruby
html = "<div class=\"logo\"><img src=\"{% image_url logo %}\" /><h1>{{ title }}</h1></div>"
safe_html = Loofah.fragment(html).scrub!(:prune).to_s
# => "<div class=\"logo\">\n<img src=\"%7B%%20image_url%20logo%20%%7D\"><h1>{{ title }}</h1>\n</div>"
```

Is there a way to use the `:prune` scrubber, but prevent the `{%` from being escaped inside the src attribute?

Thanks!

**Comment by flavorjones** [comment]
@ndbroadbent Thanks for asking this question. I'm going to merge it into #152 which is the same issue but for `href` attributes. Please collaborate with me there?
