### ISSUE TITLE
Add git tag for v2.3.0

### ISSUE THREAD

**Issue by etiennebarrie** [flavorjones/loofah#169]
It looks like the tag is missing for `v2.3.0`. As far as I can tell from the gemspec being changed from `v2.2.3` but the README not including the last changes from master, the tag should be on bcbd7b373176db3b4b2b249caaf196b625779c1b.

Thanks!

**Comment by flavorjones** [comment]
Sorry! Forgot to `git push --tags`. Done now, will update release notes.

**Comment by flavorjones** [comment]
NOTE: tag is on f6d4c2d

**Comment by etiennebarrie** [comment]
That's a bit unexpected, given the gemspec at f6d4c2d gives e.g. `rake` at `>= 0.8`:
https://github.com/flavorjones/loofah/blob/f6d4c2d1b094e33848ed454f4a69f3c12cd44084/loofah.gemspec#L28
whereas rubygems reports it at `~> 12.3`: https://rubygems.org/gems/loofah/versions/2.3.0

But if I check out v2.3.0 and build the gem, I get the same result as rubygems:
```
$ git checkout v2.3.0
$ bundle
$ bundle exec rake gem
$ echo metadata.gz | tar -x -C pkg/ -f pkg/loofah-2.3.0.gem -T -
$ gzcat pkg/metadata.gz | grep rake -A 12 -B 1
- !ruby/object:Gem::Dependency
  name: rake
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '12.3'
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '12.3'
```

So now I understand, it's because the dev dependencies were updated in 08fee8c85fb9e1c5a910491c1f5a8f8926a0600d, which is the parent of `v2.3.0`, and `hoe` uses whatever is in Rakefile, not what is in the gemspec.

Thanks again!
