### ISSUE TITLE
scrub removes 'script' tag but not the code inside it

### ISSUE THREAD

**Issue by kumarvivek2018** [flavorjones/loofah#174]
In the following code, scrubber should remove the script tag and code inside that tag. But it is **only** removing the 'script' tag.

```
  scrubber = Rails::Html::TargetScrubber.new
  scrubber.tags = ['script']

  test = "<p> askjflkasjf </p> <script> slkdjflksjdflaljl </script>"

  html_fragment = Loofah.fragment(test)
  puts html_fragment

```
#output: #<Loofah::HTML::DocumentFragment:0x3fd3fd16d51c name="#document-fragment" children=[#<Nokogiri::XML::Element:0x3fd3fd16ccd4 name="p" children=[#<Nokogiri::XML::Text:0x3fd3feff1c68 " askjflkasjf ">]>, #<Nokogiri::XML::Text:0x3fd3fd16ca54 " ">, #<Nokogiri::XML::Element:0x3fd3fd16c8c4 name="script" children=[#<Nokogiri::XML::CDATA:0x3fd3feff17e0 " slkdjflksjdflaljl ">]>]>

```
  html_fragment.scrub!(scrubber)

  puts html_fragment

```

#output: #<Loofah::HTML::DocumentFragment:0x3fd3fd16d51c name="#document-fragment" children=[#<Nokogiri::XML::Element:0x3fd3fd16ccd4 name="p" children=[#<Nokogiri::XML::Text:0x3fd3feff1c68 " askjflkasjf ">]>, #<Nokogiri::XML::Text:0x3fd3fd16ca54 " ">, #<Nokogiri::XML::Text:0x3fd3f1438898 " slkdjflksjdflaljl ">]> 

```
  test = html_fragment.to_s

  puts test

```

#output: "<p> askjflkasjf </p>  slkdjflksjdflaljl "`

I do not know why it is happening. Is it intended behavior to not delete children nodes of the node to be deleted?

**Comment by flavorjones** [comment]
Hi, thanks for asking this question. The behavior you're asking about, whether the subtree is pruned or else only the tag is removed, is entirely up to the scrubber. Loofah has builtin scrubbers that do both:

* `:prune` for pruning the entire subtree (script tag and child nodes)
* `:strip` for replacing unsafe tags with their inner text

You can read more about this in [Loofah's README](https://github.com/flavorjones/loofah/blob/master/README.md#loofahscrubber).

You may want to submit a github issue with whatever project is the source of `Rails::Html::TargetScrubber` if you have concerns about the scrubber's behavior.
