### ISSUE TITLE
Size "rem" is filtered in scrubber

### ISSUE THREAD

**Issue by alexkoy** [flavorjones/loofah#176]
Because of the CSS_KEYWORDISH-Regex in lib/loofah/html5/scrub.rb, the Size "rem" is filtered in style-attributes like "margin-top:10rem".

The style-attribute will not be removed If the Regex will be extended like this:
/\A(#[0-9a-f]+|rgb\(\d+%?,\d*%?,?\d*%?\)?|-?\d{0,2}\.?\d{0,2}(cm|em|ex|in|mm|pc|pt|px|%|,|\))?)\z/

**Comment by flavorjones** [comment]
Thanks for reporting this. I've created a fix for this that's at #177 and making its way through CI now.
