### ISSUE TITLE
Allow specific comments

### ISSUE THREAD

**Issue by danema** [flavorjones/loofah#184]
I'm using Loofah for emails sent from my application.
Although I understand that comments are stripped for a good reason, some emails contain comments to be supported by Outlook like:

`<!--[if gte mso 9]>`
and
`<![endif] -->`

If these are stripped these emails won't show properly in Outlook.
Is there any way to whitelist specific comments like the ones mentioned above?

**Comment by flavorjones** [comment]
@danema Thanks for asking this. Please give me a few hours to get back to you with a thoughtful response.

**Comment by danema** [comment]
@flavorjones, thanks for the quick reply.
Very much appreciated!

**Comment by flavorjones** [comment]
Hi @danema, thanks for your patience.

The default scrubbers must continue to try to be secure-by-default, and thus remove all comments.

However, you should be able to write your own scrubber to keep some of these browser-version-specific comments around. I played with this a bit, and something like this might do the trick for you?

```ruby
#! /usr/bin/env ruby

require "loofah"

class PermitSomeComments < Loofah::Scrubbers::Strip
  def scrub(node)
    return CONTINUE if node.comment? && node.text =~ /^\[if .*\]>.*<!\[endif\]$/m
    super
  end
end

HTML = <<EOF
<html>
  <head>
    <!--[if gte mso 9]>
      <style>
        /* browser-specific style content */
      </style>
    <![endif]-->
    <style>
      /* common style content */
    </style>
    <!-- random comment to remove -->
  </head>
  <body>
    <!--[if gte mso 9]>
      <div>browser markup</div>
    <![endif]-->
    <div>common markup</div>
    <!-- another random comment to remove -->
  </body>
</html>
EOF

# just to compare against the default scrubber behavior
puts Loofah.document(HTML).scrub!(:strip)
# >> <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
# >> <html>
# >>   <head>
# >> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
# >>
# >>
# >>       /* common style content */
# >>
# >>
# >>   </head>
# >>   <body>
# >>
# >>     <div>common markup</div>
# >>
# >>   </body>
# >> </html>

# our new scrubber allows these browser-version comments but not other comments
puts Loofah.document(HTML).scrub!(PermitSomeComments.new)
# >> <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
# >> <html>
# >>   <head>
# >> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
# >>     <!--[if gte mso 9]>
# >>       <style>
# >>         /* browser-specific style content */
# >>       </style>
# >>     <![endif]-->
# >>
# >>       /* common style content */
# >>
# >>
# >>   </head>
# >>   <body>
# >>     <!--[if gte mso 9]>
# >>       <div>browser markup</div>
# >>     <![endif]-->
# >>     <div>common markup</div>
# >>
# >>   </body>
# >> </html>
```

WARNING, THOUGH: **don't do this unless you trust the document**. Unfortunately it's possible to embed comments with javascript, and that would allow untrusted people to inject js into your document.

**Comment by flavorjones** [comment]
I'll leave this open for a few days in case you have questions -- otherwise, I hope this was helpful!
