### ISSUE TITLE
Patch notes for 2.5 / 2.6?

### ISSUE THREAD

**Issue by jmjohnson** [flavorjones/loofah#189]
Howdy, I bumped loofah from 2.5 to 2.6 in order to satisfy a devise dependency, but it doesn't look like there's been any patch notes for the last two minor releases. Is there anything different besides the version number?

![Releases_·_flavorjones_loofah](https://user-images.githubusercontent.com/604154/86840408-a5dfd000-c070-11ea-82b8-7ae047a7a5c6.png)

**Comment by jmjohnson** [comment]
Never mind; I just noticed the "version bump". Derp.

**Comment by flavorjones** [comment]
Sorry - I sometimes forget people care about the release notes. I'll add them now. But if I forget in the future, there's a `CHANGELOG.md` in the repo that *is* kept up to date: https://github.com/flavorjones/loofah/blob/master/CHANGELOG.md
