### ISSUE TITLE
scrub_css drops !important rule from shorthand css properties

### ISSUE THREAD

**Issue by b7kich** [flavorjones/loofah#191]
Applies to shorthand CSS properties like border, padding, margin, background and their expansions like margin-top, background-color etc. 
```ruby
[1] pry(main)> puts Loofah::fragment('<h1 style="background: black !important; color: white !important; ">got milk?</h1>').scrub!(:prune)
<h1 style="background:black;color: white !important;">got milk?</h1>
```

**Comment by flavorjones** [comment]
Thanks for reporting this. I'll take a look at the PR at #192 today.

**Comment by flavorjones** [comment]
Will ship in v2.7.0 later today.

**Comment by flavorjones** [comment]
https://github.com/flavorjones/loofah/releases/tag/v2.7.0

**Comment by b7kich** [comment]
Thanks for cleaning the code up!

**Comment by flavorjones** [comment]
No, thank you for figuring out the bug and submitting a PR! This was a tricky one. :+1:
