### ISSUE TITLE
Empty data attributes are stripped

### ISSUE THREAD

**Issue by ryanb** [flavorjones/loofah#215]
Is there a reason why empty data attributes are stripped?

```ruby
Loofah.fragment('<div data-foo></div>').scrub!(:prune).to_s
 #=> "<div></div>"
Loofah.fragment('<div data-foo="bar"></div>').scrub!(:prune).to_s
 #=> "<div data-foo=\"bar\"></div>"
```

From what I can tell, empty data attributes are valid in HTML 5.

**Comment by flavorjones** [comment]
Hi @ryanb, thanks for reporting this. I agree, empty `data-*` attributes are valid and I think this behavior is just an oversight. Support for `data-*` attributes was added in #59 and expanded in #84 but at no point were empty attributes tested.

I think I can get to this in the next day or two, hang tight!

**Comment by flavorjones** [comment]
v2.12.0 has been released with a fix: [Release 2.12.0 / 2021-08-11 · flavorjones/loofah](https://github.com/flavorjones/loofah/releases/tag/v2.12.0)

**Comment by ryanb** [comment]
Wow thanks for the fast turnaround! I really appreciate the work you put into loofah.

**Comment by flavorjones** [comment]
Ah, thanks for the kind words.
