### ISSUE TITLE
Adding sms to ACCEPTABLE_PROTOCOLS

### ISSUE THREAD

**Issue by brendon** [flavorjones/loofah#228]
Hi there, would you be open to adding `sms` to `ACCEPTABLE_PROTOCOLS`?

Seems a strange one to miss given `tel` is there :)

**Comment by flavorjones** [comment]
Hi, @brendon! Sure, that seems like a fine protocol to add, I'd love if you submitted a pull request.

Check out a1b1da9 for an example commit of a previous addition to protocols.

**Comment by brendon** [comment]
Sure can (and have)! :) Thanks for the quick response. I just wanted to check if there was a reason for excluding sms before I went ahead with the PR :)

**Comment by flavorjones** [comment]
Released in v2.15.0
