### ISSUE TITLE
Loofah removes &nbsp;

### ISSUE THREAD

**Issue by wizardofosmium** [flavorjones/loofah#240]
There are times when `&nbsp;` is actually needed.  Unfortunately, `Loofah` removes them.
```ruby
> Loofah.fragment("&amp;nbsp; != &nbsp;").to_s
=> "&amp;nbsp; !=  "
```

Could you either make:

- `Loofah` not remove them at all, or
- provide an option to keep them?

**Comment by flavorjones** [comment]
Hi! This unfortunately is not behavior that Loofah directly controls, it's how libxml2 parses:

```
>> x = Nokogiri::HTML4::DocumentFragment.parse("&amp;nbsp; != &nbsp;")
=> 
#(DocumentFragment:0xc300 {                                              
...                                                                      
>> x.to_html
=> "&amp;nbsp; !=  "
>> x
=> 
#(DocumentFragment:0xc300 {                                              
  name = "#document-fragment",                                           
  children = [ #(Text "&nbsp; !=  ")]                                    
  })                                                                     
```

although the gumbo parser used by `Nokogiri::HTML5` is better:

```
>> x = Nokogiri::HTML5::DocumentFragment.parse("&amp;nbsp; != &nbsp;")
=> 
#(DocumentFragment:0xe894 {                                              
...                                                                      
>> x.to_html
=> "&amp;nbsp; != &nbsp;"
>> x
=> 
#(DocumentFragment:0xe894 {          
  name = "#document-fragment",       
  children = [ #(Text "&nbsp; !=  ")]
  })                                 
```

Because this behavior is inherited from libxml2, there's nothing we can easily do in Nokogiri or Loofah to change it.

Note that we're planning to update Loofah to use Nokogiri::HTML5 when it's available: https://github.com/flavorjones/loofah/pull/239 which is blocked on Nokogiri v1.14.0 being released (soon!).

**Comment by wizardofosmium** [comment]
Thanks for the explanation @flavorjones 👍 

It looks like I'll have to hack around it with something like:
```ruby
string = "&amp;nbsp; != &nbsp; or &#160;"
protected_string = string.gsub(/&nbsp;/, "PROTECTEDNBSP").gsub(/&#160;/, "PROTECTED160")
Loofah.fragment(protected_string).to_s.gsub(/PROTECTEDNBSP/, "&nbsp;").gsub(/PROTECTED160/, "&#160;")
```
(Just have to hope that the input doesn't contain PROTECTEDNBSP or PROTECTED160 😬)

Any other suggestions would be welcome.  Cheers!

**Comment by Yegorov** [comment]
Hello everyone, thanks for the answers!
Loofah removes not only `&nbsp;` Also removes `&mdash;` `&laquo;` `&raquo;` and others
For my case it looks like this:
```ruby
string = "&amp;nbsp; &nbsp; &#160; &mdash; &laquo; &raquo;"
protected_string = string.gsub(/&(.+?);/, '_PROTECTED\1_')
Loofah.fragment(protected_string).to_s.gsub(/_PROTECTED(.+?)_/, '&\1;')
```
