### ISSUE TITLE
Preserving emails that look like tags

### ISSUE THREAD

**Issue by hahuang65** [flavorjones/loofah#250]
I have some user-generated content that contain email addresses that look like tags, such as addresses in email headers that look like:

```
From: Smith, John <jsmith@example.com>
```

After using `sanitize()` on it, it becomes: `From: Smith, John`, but I'd like to keep the email around.

After playing around with a custom scrubber, I can't figure out how to exclude these successfully.
`node.content` is blank on these, `node.name` is just the front part of the email (I think the parser thinks it's an HTML tag and ignores the section after the `@`).

For example, `<jsmith@example.com>`, becomes `jsmith` as the `node.name`.

Any suggestions would be greatly appreciated!

**Comment by flavorjones** [comment]
Hi! Thanks for asking this question.

Loofah is intended to scrub XML or HTML. If the string "From: Smith, John <jsmith@example.com>" is present in an XML or HTML doc, it's invalid. The `<` and `>` characters need to be escaped in text nodes, or else the parser will fail to parse.

```ruby
frag = Nokogiri::HTML.fragment("<div> Smith, John <jsmith@example.com> </div>")
frag.errors
# => [#<Nokogiri::XML::SyntaxError: 1:38: ERROR: error parsing attribute name>,
#     #<Nokogiri::XML::SyntaxError: 1:50: ERROR: Tag jsmith invalid>]       
frag.to_html
# => "<div> Smith, John <jsmith> </jsmith>\n</div>"
```

Does that make sense?

If you don't have an HTML fragment and just have a string, you may want to run `CGI.escapeHTML` on it first:

```ruby
html = CGI.escapeHTML("Smith, John <jsmith@example.com>")
# => "Smith, John &lt;jsmith@example.com&gt;"
```

I hope this helps!

**Comment by hahuang65** [comment]
Very helpful, thank you for the quick response as well!
