### ISSUE TITLE
whitewash test error with libxml 2.9.1

### ISSUE THREAD

**Issue by ktdreyer** [flavorjones/loofah#60]
I'm seeing a test failure with the newer LibXML 2.9.0 in Fedora 19 and above: 

```
=> testing with Nokogiri {"warnings"=>["Nokogiri was built against LibXML version 2.9.0, but has dynamically loaded 2.9.1"], "nokogiri"=>"1.5.9", "ruby"=>{"version"=>"2.0.0", "platform"=>"i386-linux", "description"=>"ruby 2.0.0p353 (2013-11-22 revision 43784) [i386-linux]", "engine"=>"ruby"}, "libxml"=>{"binding"=>"extension", "compiled"=>"2.9.0", "loaded"=>"2.9.1"}}
```

The same test succeeds on CentOS 6, with Ruby 1.9.3 and LibXML 2.8.0:

```
=> testing with Nokogiri {"warnings"=>[], "nokogiri"=>"1.6.1", "ruby"=>{"version"=>"1.9.3", "platform"=>"x86_64-linux", "description"=>"ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-linux]", "engine"=>"ruby"}, "libxml"=>{"binding"=>"extension", "source"=>"packaged", "libxml2_path"=>"/home/gitoriousci193/.gems/gems/nokogiri-1.6.1/ports/x86_64-redhat-linux/libxml2/2.8.0", "libxslt_path"=>"/home/gitoriousci193/.gems/gems/nokogiri-1.6.1/ports/x86_64-redhat-linux/libxslt/1.1.26", "compiled"=>"2.8.0", "loaded"=>"2.8.0"}}
```

The failing test is this one:

```
  1) Failure:
IntegrationTestAdHoc#test_fragment_whitewash_on_microsofty_markup [/builddir/bui
ld/BUILD/loofah-1.2.1/usr/share/gems/gems/loofah-1.2.1/test/integration/test_ad_
hoc.rb:146]:
--- expected
+++ actual
@@ -1 +1,4 @@
-"<p>Foo <b>BOLD</b></p>"
+"
+
+<p>Foo <b>BOLD</b></p>
+"
```

For some reason, nokogiri must be inserting some blank lines there.

I looked at the Travis builds, and apparently Travis is using the older LibXML 2.8.0, which might explain why we haven't seen this fail in Travis yet.

**Comment by ktdreyer** [comment]
The tests no longer fail on Fedora 23 with Nokogiri 1.6.6.2, Ruby 2.2.2p95, and libxml 2.9.2.

What do you think about bumping the minimum required version of Nokogiri in loofah.gemspec from 1.5.9 to this newer version?

**Comment by flavorjones** [comment]
Sorry for the delay in replying and closing this. I'm almost positive this was due to bugs in libxml 2.9.0 and 2.9.1, and modern version of Nokogiri either patched that behavior or have later versions of libxml2 vendored.

Closing.
