### ISSUE TITLE
Not all CSS properties are whitelisted

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/loofah#68]
One example is `word-spacing`, which is listed at http://www.w3.org/TR/CSS2/propidx.html but isn't included in Loofah's whitelist (or the whitelist in html5lib-ruby which is obviously not being maintained anymore).

There's a greated problem here of keeping whitelists up to date with specs. Perhaps we can solve both.

**Comment by doooks** [comment]
list-style-type is another missing property. If I did a PR to introduce all the properties from the CSS spec is that likely to be accepted?

**Comment by flavorjones** [comment]
@doooks note that #142 is about to be merged which addresses `list-style-type` specifically.

**Comment by flavorjones** [comment]
Note that this was addressed in v2.2.0. Sorry for not closing in a timely manner!
