### ISSUE TITLE
Confirm that all HTML5 tags are whitelisted

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/loofah#69]
Canonical list here:

http://www.w3.org/TR/html-markup/elements.html

**Comment by wilg** [comment]
@flavorjones Is there a reason `source`  and `track` were not included? Without this, HTML5 `video` and `audio` are hamstrung.

**Comment by wilg** [comment]
Some vulnerabilities noted here: https://html5sec.org/#55

**Comment by bricesanchez** [comment]
This should fix #108 and refinery/refinerycms#3138
