### ISSUE TITLE
#to_text should preserve whitespace between inline elements

### ISSUE THREAD

**Issue by timherby** [flavorjones/loofah#71]
@flavorjones I love the that #to_text preserves whitespace (as you added here https://github.com/flavorjones/loofah/issues/12), but it doesn't appear to preserve between inline elements as you say in this post (https://github.com/sparklemotion/nokogiri/issues/636), only block elements.  Would it be reasonable for it to preserve whitespace between inline elements?  Am I missing an option to do this?  If not, would you be open to a pull request to make this happen?

**Comment by flavorjones** [comment]
I'm open to a PR of some sort that generates output as you describe. Let me know if you'd like direction or advice?
