### ISSUE TITLE
`#to_text` with saner inner whitespace and newline handling

### ISSUE THREAD

**Issue by thegcat** [flavorjones/loofah#82]
Something like

``` html
<p>foo
bar   baz</p>
```

will yield

```
\nfoo\nbar   baz\n
```

when passed through Loofah and `to_text`. Browsers will render that as `foo bar baz` though. Is there any built-in way, either in Loofah or Nokogiri, to collapse whitespaces and replace non-significant newlines with whitespace to better match the text that would be shown in a browser?

**Comment by flavorjones** [comment]
Hi, apologies for the atrociously long delay in responding.

It's a bit beyond the mandate of Loofah to generate output that both matches human and browser expectations. I don't want to tell you that this wouldn't be valuable; but that the work we'd need to put in to make this work, and the fuzziness around how different humans have different definitions of "human readable", make this feel very hard to be successful.

I'm happy to look at PRs that might provide some measure of support around this; but for now I'll close this issue. Please comment if you'd like to start on a PR, happy to help.

**Comment by flavorjones** [comment]
It looks like a PR might just be able to modify this method to accomplish what you want:

```ruby
    def remove_extraneous_whitespace(string)
      string.gsub(/\n\s*\n\s*\n/,"\n\n")
    end
```

**Comment by thegcat** [comment]
It seems there's a misunderstanding here, either I don't quite understand what you are proposing, or I was not able to communicate what we hope to achieve :-)

The point is not to remove extraneous whitespace, the point is to not emit newlines included in the HTML input into loofah but that would not be rendered as line breaks when rendered as newlines in the text output of loofah.

In the example I gave above, there is a newline in the HTML inside the `<p>` block that a browser would ignore, i.e. it would be rendered as one line instead of 2. Multiple whitespaces in the `<p>` block in the HTML would also be collapsed to one whitespace in the result rendered by a browser, but that is less of a concern for now.

Unfortunately this is not something that would be possible to "post-process" as I do not think there is a way to differentiate newlines that were part of the original HTML from newlines introduced by loofah as for example delimiter between `<p>` blocks, is there? Furthermore, there wouldn't be any way to discern newlines in `<p>` blocks where they are not significant from newlines in `<pre>` where they are significant, or even from `<br>`s that turn into significant newlines.

Was I able to make my question more clear? Or am I still missing something from your answer? Thanks!
