### ISSUE TITLE
Option to not remove comments on scrub!

### ISSUE THREAD

**Issue by brauliobo** [flavorjones/loofah#86]
Is there a way to NOT remove comments on `scrub!`?

**Comment by brauliobo** [comment]
Just adding `COMMENT_NODE` to `htmllib_sanitize` solved:
```ruby
# do not escape COMMENT_NODE                                                        
require 'loofah/scrubber'                                                           
module Loofah
  class Scrubber
    private
  
    def html5lib_sanitize node                                                      
      case node.type                                                                
      when Nokogiri::XML::Node::ELEMENT_NODE                                        
        if HTML5::Scrub.allowed_element? node.name                                  
          HTML5::Scrub.scrub_attributes node                                        
          return Scrubber::CONTINUE
        end
      when Nokogiri::XML::Node::TEXT_NODE, Nokogiri::XML::Node::CDATA_SECTION_NODE,Nokogiri::XML::Node::COMMENT_NODE
        return Scrubber::CONTINUE                                                   
      end
      Scrubber::STOP
    end 
      
  end 
end 
```

**Comment by flavorjones** [comment]
Hi! Thanks for asking this question.

Can you tell me a little bit more about your use case? What do you want to do that Loofah's not currently allowing you to do? Can you share the code snippet and test case that tells me what you'd like to do?

**Comment by brauliobo** [comment]
Loofah is removing HTML comments, which I find useful and always safe to have, for example:
```html
<html>
<body>
   <!-- my comment about something -->
</body>
</html>
```
The above comment is removed by Loofah.

**Comment by Qqwy** [comment]
Another usecase would be (*cringes*...) IE conditional comments.

**Comment by flavorjones** [comment]
@Qqwy the reason that comments are scrubbed is precisely what you suggest; that there would be unescaped HTML in the comment that would be executed by the browser.

Given that, I guess we could recursively escape the contents of the comment, similar to what we do with the contents of a `script` tag (see #132 for specifics) ... my question, given the lack of activity in this issue, is: is it worth the effort?

Would love to hear what Loofah and Rails users think.

**Comment by flavorjones** [comment]
It looks like there's not interest in addressing this concern, so I'm closing this issue.
