### ISSUE TITLE
scrub! truncates large text

### ISSUE THREAD

**Issue by FlySnake** [flavorjones/loofah#89]
I have a large text file https://yadi.sk/d/tpPMTsjWhKjTM (raw.txt).
```
data = File.read('/Users/oleg_antonyan/Desktop/raw.txt')
data.length
=> 423459
Loofah.fragment(data).scrub!(:strip).to_html.length
=> 33815
Loofah.fragment(data).scrub!(:escape).to_html.length
=> 46827
Loofah.fragment(data).scrub!(:prune).to_html.length
=> 6665
Loofah.fragment(data).scrub!(:whitewash).to_html.length
=> 6665
Loofah.fragment(data).scrub!(:nofollow).to_html.length
=> 42921
Loofah.fragment(data).scrub!(:unprintable).to_html.length
=> 42921
```
Notice 10 times smaller text length. It can't be right.

**Comment by flavorjones** [comment]
Hi!

You're scrubbing plain text, so I'm curious what you *expect* to have happen when you remove anything that looks like an illegal tag. There are lots of "<" characters, so I'm not surprised that libxml2 is getting confused when it looks at it.

I'd stick with `scrub!(:escape)` which will escape those characters; anything else requires that you pass in HTML or XML. Make sense?

**Comment by flavorjones** [comment]
Also, for future reference, questions like this are really better asked on the mailing list, for reasons explained at http://bit.ly/nokohelp.

Thanks for using Nokogiri!

**Comment by FlySnake** [comment]
Ok, thanks for quick response!

The reason why I'm doing this on a plain text is that I need to display the text on a web page with rails. But also I need to highlight some words in this text.

There is `highlight` function in rails which does exactly what I need (like this `highlight(@build_log.text, "error", highlighter: '<b><mark class="bg-danger">\1</mark></b>')`). But `highlight` function in rails uses `scrub!(:strip)` internally.

**Comment by flavorjones** [comment]
Hmm, that's odd, you could always have Loofah :escape the text before you
pass it into highlighting?

Good luck!

**Comment by FlySnake** [comment]
Actually,  Loofah :escape also truncates the text
```
data = File.read('/Users/oleg_antonyan/Desktop/raw.txt')
data.length
=> 423459
Loofah.fragment(data).scrub!(:escape).to_html.length
=> 46827
```

**Comment by flavorjones** [comment]
Hmm, then my last suggestion would be to use `CGI.escapeHTML` to escape the
HTML entities before you sent it into the parser+sanitizer.

**Comment by FlySnake** [comment]
Yep! WIth CGI.escapeHTML it works.
