### ISSUE TITLE
Replacing nodes with <br> tag

### ISSUE THREAD

**Issue by lbrito1** [flavorjones/loofah#92]
Hi,

Consider the following fragment:

`fragment = '<h1>Motorola Moto W</h1><br><br>Um celular.<br> <br><table><tr><td>Coluna 1</td><td>Coluna 2</td></tr></table>'`

I'd like to replace a few tags with `<br>`s (two per node). For example, say I wish to replace `<tr>` with `<br>`, I'd expect something like:

`'<h1>Motorola Moto W</h1><br><br>Um celular.<br> <br><table><br><td>Coluna 1</td><td>Coluna 2</td><br></table>'`

Is this possible? The closest I've achieved is this:

    table2br = Loofah::Scrubber.new {|node| node.name = 'br' if node.name == 'tr' }
    Loofah.fragment(fragment).scrub!(table2br).to_s

Which results in the following: 

`"<h1>Motorola Moto W</h1><br><br>Um celular.<br> <br><table><br></table>"`

As you can see, `<br>` replaces the entire node.

**Comment by flavorjones** [comment]
Thanks for asking this question, but I don't think there's a problem here.

I wrote code to attempt to reproduce what you're seeing (next time, it would help me if you provided this code yourself):

```ruby
#! /usr/bin/env ruby

require 'loofah'

html = '<h1>Motorola Moto W</h1><br><br>Um celular.<br> <br><table><tr><td>Coluna 1</td><td>Coluna 2</td></tr></table>'

fragment = Loofah.fragment(html)

puts fragment
puts "---"

table2br = Loofah::Scrubber.new {|node| node.name = 'br' if node.name == 'tr' }

puts fragment.scrub!(table2br)
```

and the output is:

```
<h1>Motorola Moto W</h1><br><br>Um celular.<br> <br><table><tr>
<td>Coluna 1</td>
<td>Coluna 2</td>
</tr></table>
---
<h1>Motorola Moto W</h1><br><br>Um celular.<br> <br><table><br></table>
```

I'll indent it so it's obvious:

```
<h1>Motorola Moto W</h1><br><br>Um celular.<br> <br>
<table>
  <tr>
    <td>Coluna 1</td>
    <td>Coluna 2</td>
  </tr>
</table>
---
<h1>Motorola Moto W</h1><br><br>Um celular.<br> <br>
<table>
  <br>
</table>
```

Hopefully you can see that the single `<tr>` tag is being replaced with a single `<br>` tag. Does that make sense?

**Comment by flavorjones** [comment]
If I've misunderstood your issue, please let me know and I'll try to help.

**Comment by flavorjones** [comment]
Specifically, provide the markup you wish to emit. Again, it would really help me if you provided working code.

**Comment by lbrito1** [comment]
Hi, thanks for the answer. Sorry about not providing a SSCCE.

The behavior you described makes sense but is not exactly what I expected - I'll try to explain why. As I see it, `node.name = 'x'` should change the tag to x, not replace the content. This is indeed the case with non-empty HTML tags, but not with `<br>`. I understand your point though: since `<br>` has no children, when replacing `<tr>` with `<br>`, the table columns disappear. 

My question is if there's any way of replacing opening and closing tags with `<br>` using Loofah. This will not always make sense (in fact, replacing `<tr>` - bad example! - would be troublesome because of the children nodes), but might prove useful in some cases. My goal is actually to replace the `<td>`s in the example.

**Comment by flavorjones** [comment]
@lbrito1 Ah - OK, I think I understand what's going on.

Let's take the snippet I used in my previous response, and compare the fragment HTML markup emitted to the XML markup emitted:

```
puts fragment.to_html
# => <h1>Motorola Moto W</h1><br><br>Um celular.<br> <br><table><br></table>

puts fragment.to_xml
# => <h1>Motorola Moto W</h1><br/><br/>Um celular.<br/> <br/><table>
#       <br>
#         <td>Coluna 1</td>
#         <td>Coluna 2</td>
#       </br>
#     </table>
```

What's happening here is that libxml2 is smart enough to emit only valid HTML. Asking it to emit children of `<br>` would be invalid HTML, and so it doesn't do it. Only when you ask for XML will it emit the children.

So, there's your workaround -- treat it like it's XML, not HTML, if you're going to create invalid HTML. You can do this with `#to_xml` or you can start with `.xml_fragment` in place of `.fragment`.

(Although, I'm not sure what the point of generating invalid HTML is -- browsers will likely all handle this differently.)
