### ISSUE TITLE
The Loofah.fragment method does not work as expected

### ISSUE THREAD

**Issue by chumakoff** [flavorjones/loofah#99]
Loofah.fragment("one < two")
=> one

Related issues:
https://github.com/sparklemotion/nokogiri/issues/1419
https://github.com/rails/rails/issues/23230

**Comment by chumakoff** [comment]
rails-html-sanitizer (1.0.2)
loofah (2.0.3)

**Comment by flavorjones** [comment]
Thanks for asking this question. I'll repeat here what I said in the nokogiri issue:

Nokogiri uses XML parsing libraries under the hood (libxml2 for MRI, xerces/nekohtml for JRuby) and so we have very little control over how those libraries decide to "fix" broken markup.
